title: AR Law Counsel
author: Ameer Riaz
description: Privacy Compliance & Civil Litigation Experts

# The Cyber-Tech Theme
remote_theme: pages-themes/cayman@v0.2.0

# PATH FIXES (Crucial for your URL)
baseurl: "/Ameer.R" 
url: "https://ameerriaz.github.io"

# Social Links (Theme specific)
google_analytics: 
show_downloads: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
